CimenaCityProject/Models/HomeCinema.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CimenaCityProject.Models
{
    /// <summary>
    /// Describing the HomeCinema
    /// what City he placed , address, name
    /// </summary>
    public class HomeCinema
    {

        public HomeCinema()
        {
            this.MovieTheaters = new HashSet<MovieTheaters>();
        }

        public int HomeCinemaID { get; set; }
        public string CinemaName { get; set; }
        public int CityID { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<bool> Showing { get; set; }

        public virtual CityList CityList { get; set; }
        public virtual ICollection<MovieTheaters> MovieTheaters { get; set; }
    }
}

CimenaCityProject/Controllers/HomeCinemaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

using CimenaCityProject.Models;
using CimenaCityProject.ViewModels;

namespace CimenaCityProject.Controllers
{
    public class HomeCinemaController : Controller
    {
        private HomeCinemaContext db = new HomeCinemaContext();

        // GET: /HomeCinema/
        public ActionResult Index(string sortingOrder)
        {
            var result = new List<HomeCinema>();
            if (!string.IsNullOrEmpty(sortingOrder))
            {
                switch (sortingOrder)
                {
                    case "CinemaName":
                        result = db.HomeCinemas.OrderBy(x => x.CinemaName).ToList();
                        break;
                    case "City":
                        result = db.HomeCinemas.OrderBy(x => x.CityID).ToList();
                        break;
                    case "Address":
                        result = db.HomeCinemas.OrderBy(x => x.Address).ToList();
                        break;
                    case "PhoneNumber":
                        result = db.HomeCinemas.OrderBy(x => x.PhoneNumber).ToList();
                        break;
                    case "Showing":
                        result = db.HomeCinemas.OrderByDescending(x => x.Showing).ToList();
                        break;
                    default:
                        result = db.HomeCinemas.ToList();
                        break;
                }
            }
            else
            {
                result = db.HomeCinemas.ToList();
            }
            return View(result);
        }

        // GET: /HomeCinema/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HomeCinema homecinema = db.HomeCinemas.Find(id);
            if (homecinema == null)
            {
                return HttpNotFound();
            }
            return View(homecinema);
        }

        // GET: /HomeCinema/Create
        public ActionResult Create()
        {
            ViewBag.CityID = new SelectList(db.CityList.ToArray(), "CityID", "EnglishName");
            ViewBag.ErrorMassage = "";
            return View();
        }


        // POST: /HomeCinema/Create
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "HomeCinemaID,CinemaName,City,Address,PhoneNumber")]HomeCinema homeCinema,int? number, int? CityID)
        {
           
            if (!CityID.HasValue)
            {
                ViewBag.ErrorMassage = "You must Select a City. ";
                ViewBag.CityID = new SelectList(db.CityList.ToArray(), "CityID", "EnglishName");
                return View(homeCinema);
            }
            homeCinema.CityID = CityID.Value;

            // Check if the homeCinema is alredy enterd. 
            foreach (var Cinema in db.HomeCinemas)
            {
                if (Cinema.CityID == homeCinema.CityID && Cinema.CinemaName == homeCinema.CinemaName)
                {
                    ViewBag.ErrorMassage = "You cant add this Theatres again. Choose another name.";
                    ViewBag.CityID = new SelectList(db.CityList.ToArray(), "CityID", "EnglishName");

                    return View();
                }
            }

            if (ModelState.IsValid)
            {
                db.HomeCinemas.Add(homeCinema);
                db.SaveChanges();

                homeCinema = db.HomeCinemas.Where(x => x.CinemaName == homeCinema.CinemaName).FirstOrDefault();
                return RedirectToAction("Create", "Theatres", new { id = homeCinema.HomeCinemaID , number = number});
            }

            ViewBag.CityID = new SelectList(db.CityList.ToArray(), "CityID", "EnglishName");
            return View(homeCinema);
        }

        // GET: /HomeCinema/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
           
            HomeCinema homecinema = db.HomeCinemas.Find(id);
            if (homecinema == null)
            {
                return HttpNotFound();
            }
            ViewBag.CityID = new SelectList(db.CityList, "CityID", "EnglishName",homecinema.CityID);
            return View(homecinema);
        }

        // POST: /HomeCinema/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="HomeCinemaID,CinemaName,City,Address,PhoneNumber")] HomeCinema homecinema, int? CityID)
        {
            if (!CityID.HasValue)
            {
                ViewBag.CityID = new SelectList(db.CityList.ToArray(), "CityID", "EnglishName");
                return View(homecinema);
            }
            homecinema.CityID = CityID.Value;
            if (ModelState.IsValid)
            {
                db.Entry(homecinema).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CityID = new SelectList(db.CityList.ToArray(), "CityID", "EnglishName");
            return View(homecinema);
        }

        // GET: /HomeCinema/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            HomeCinema homecinema = db.HomeCinemas.Find(id);
            if (homecinema == null)
            {
                return HttpNotFound();
            }
            return View(homecinema);
        }

        // POST: /HomeCinema/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            HomeCinema homecinema = db.HomeCinemas.Find(id);
            db.HomeCinemas.Remove(homecinema);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public PartialViewResult Error(string ErrorMessge)
        {
            TempData.Add("error", ErrorMessge);
            return PartialView();
        }

        private HomeCinemaDetails homeCinemaDetails(string _switch, int? id)
        {
            return new HomeCinemaDetails(_switch, id);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

       

    }
}

CimenaCityProject/Views/HomeCinema/Create.cshtml
@using CimenaCityProject.Models
@model CimenaCityProject.Models.HomeCinema

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
<h4>New Home Cinema</h4>

@using (Html.BeginForm("Create", "HomeCinema", FormMethod.Post, new { id = "HomeCinema", name = "HomeCinema" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        
        <hr />

        <span>@ViewBag.ErrorMassage</span>

        @Html.ValidationSummary(true)
        @{  HomeCinemaContext db = new HomeCinemaContext();}
        <div class="form-group">
            @Html.LabelFor(model => db.CityList.Where(x => x.CityID == model.CityID).SingleOrDefault().EnglishName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CityID")
                @Html.ValidationMessageFor(model => db.CityList.Where(x => x.CityID == model.CityID).SingleOrDefault().EnglishName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CinemaName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.CinemaName)
                @Html.ValidationMessageFor(model => model.CinemaName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Address)
                @Html.ValidationMessageFor(model => model.Address)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.PhoneNumber)
                @Html.ValidationMessageFor(model => model.PhoneNumber)
            </div>
        </div>

        <span>Number Theatres to build?</span>
        <input type="number" name="number" id="number" />

       
        <div class=" form-group">
            <div class="col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>

    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}


    @*<script src="~/Scripts/jquery-1.10.2.js"></script>
        <script src="~/Scripts/jquery-1.10.2.min.js"></script>

        <script type="text/javascript">
            function getTheatresView() {
                $('#divLoading').show();
                $.ajax({
                    url: '@Url.Action()',
                    type: 'POST',
                    data: JSON.stringify({
                        homeCinema: {
                            Address: $('#Address').val(),
                            CinemaName: $('#CinemaName').val(),
                            PhoneNumber: $('#PhoneNumber').val()
                        },
                        number: $('#number').val(),
                        CityID: $('#CityID').val()

                    }),

                    contentType: 'application/json; charset=utf-8',

                    success: function (result) {
                        success(result);

                    },
                    error: function (result) {
                        alert(result.responseText + "no now ziv")
                        $('#divLoading').hide();

                    }
                });
            };
            function success(result) {
                $('#DivResult').html(result)
                $('#divLoading').hide();
                $('#Create').hide();
            }

        </script>*@

CimenaCityProject/Views/HomeCinema/Delete.cshtml
@using CimenaCityProject.Models
@model CimenaCityProject.Models.HomeCinema

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>HomeCinema</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CinemaName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CinemaName)
        </dd>

     @{ 
         HomeCinemaContext db = new HomeCinemaContext();
           <dt>
            City 
        </dt>

        <dd>
           @db.CityList.Where(x=>x.CityID==Model.CityID).SingleOrDefault().EnglishName
        </dd>}

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CimenaCityProject/Views/HomeCinema/Details.cshtml
@using CimenaCityProject.Models
@model CimenaCityProject.Models.HomeCinema

@{
    ViewBag.Title = "Details";
}

<h3>@Model.CinemaName Details</h3>
@{HomeCinemaContext db = new HomeCinemaContext();}
<div>
    <h4></h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            Cinema Name 
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CinemaName)
        </dd>

        <dt>
            English Name
        </dt>

        <dd>
            @Html.DisplayFor(model => db.CityList.Where(x => x.CityID == model.CityID).SingleOrDefault().EnglishName)
        </dd>

        <dt>
            Address
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            Phone Number
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt>
            <br />
        </dt>
        <dd>
            <br />
        </dd>
        <dt>
            Theatres
        </dt>
        <dd>
            @{
                <table>
                    @foreach (var theatr in db.Theaters)
                    {
                        if (Model.HomeCinemaID == theatr.HomeCinemaID)
                        {

                            <tr>
                                <td>
                                    @Html.DisplayName(theatr.TheatersName)
                                </td>
                                <td>
                                    <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
                                </td>
                                <td>
                                    @Html.ActionLink("Details", "Details", "Theatres", new { id = theatr.MovieTheatersID }, null)
                                </td>
                            </tr>

                        }
                    }

                </table>
            }
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.HomeCinemaID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CimenaCityProject/Views/HomeCinema/Edit.cshtml
@using CimenaCityProject.Models
@model CimenaCityProject.Models.HomeCinema

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>HomeCinema</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.HomeCinemaID)
        <div class="form-group">
            @Html.LabelFor(model => model.CinemaName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CinemaName)
                @Html.ValidationMessageFor(model => model.CinemaName)
            </div>
        </div>
        @{HomeCinemaContext db = new HomeCinemaContext();}
        <div class="form-group">
            @Html.LabelFor(model => db.CityList.Where(x => x.CityID == model.CityID).SingleOrDefault().EnglishName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CityID")
                @Html.ValidationMessageFor(model => db.CityList.Where(x => x.CityID == model.CityID).SingleOrDefault().EnglishName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address)
                @Html.ValidationMessageFor(model => model.Address)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber)
                @Html.ValidationMessageFor(model => model.PhoneNumber)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
        <br />
        <div class="form-group">
            <div class="col-md-10 col-md-offset-2">
                <table>
                    <tr>
                        <th>
                            Theatres
                        </th>
                    </tr>
                    @foreach (var item in db.Theaters)
                    {
                        if (Model.HomeCinemaID == item.HomeCinemaID)
                        {
                            <tr>
                                <td>

                                    @item.TheatersName
                                    <br />
                                </td>
                                <td>&nbsp;</td>
                                <td>
                                    @Html.ActionLink("Edit", "Edit","Theatres",new { id = item.MovieTheatersID },null )
                                </td>
                            </tr>
                        }
                    }
                </table>
            </div>
        </div>
       
        <br />      
    </div>
}


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CimenaCityProject/Views/HomeCinema/Index.cshtml
@using CimenaCityProject.Models;
@model IEnumerable<CimenaCityProject.Models.HomeCinema>

@{
    ViewBag.Title = "Index";
}
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery-ui.js"></script>
<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create") <br /> @Html.ActionLink(" Return Control Panel", "ControlPanel", "Admin")
</p>
<div id="divLoading" style="display:none">
    <img src="~/Image/Elements/ajax-loader.gif" />
</div>
<div id="divResult">
    <table class="table">
        <tr>
            <td>

                @Ajax.ActionLink("Cinema Name", "Index", new { sortingOrder = "CinemaName" }, new AjaxOptions()
                                                                    {
                                                                        HttpMethod = "GET",
                                                                        UpdateTargetId = "divResult",
                                                                        InsertionMode = InsertionMode.Replace,
                                                                        LoadingElementId = "divLoading"
                                                                    })

            </td>
            <td>
                @Ajax.ActionLink("City", "Index", new { sortingOrder = "City" }, new AjaxOptions()
                                                                    {
                                                                        HttpMethod = "GET",
                                                                        UpdateTargetId = "divResult",
                                                                        InsertionMode = InsertionMode.Replace,
                                                                        LoadingElementId = "divLoading"
                                                                    })
                
            </td>
            <td>
                @Ajax.ActionLink("Address", "Index", new { sortingOrder = "Address" }, new AjaxOptions()
                                                                    {
                                                                        HttpMethod = "GET",
                                                                        UpdateTargetId = "divResult",
                                                                        InsertionMode = InsertionMode.Replace,
                                                                        LoadingElementId = "divLoading"
                                                                    })
           
            </td>
            <td>
                @Ajax.ActionLink("Phone Number", "Index", new { sortingOrder = "PhoneNumber" }, new AjaxOptions()
                                                                    {
                                                                        HttpMethod = "GET",
                                                                        UpdateTargetId = "divResult",
                                                                        InsertionMode = InsertionMode.Replace,
                                                                        LoadingElementId = "divLoading"
                                                                    })
                
            </td>
            <td>
                Theatres
            </td>
            <td>
                @Ajax.ActionLink("Is Showing", "Index", new { sortingOrder = "Showing" }, new AjaxOptions()
                                                                    {
                                                                        HttpMethod = "GET",
                                                                        UpdateTargetId = "divResult",
                                                                        InsertionMode = InsertionMode.Replace,
                                                                        LoadingElementId = "divLoading"
                                                                    })
            </td>
            <td></td>
        </tr>

        @{  HomeCinemaContext db = new HomeCinemaContext();}
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CinemaName)
                </td>
                <td>
                    @db.CityList.Where(x => x.CityID == item.CityID).SingleOrDefault().EnglishName
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                </td>
                <td>
                    @{
                        <table>
                            @foreach (var theatr in db.Theaters)
                            {
                                if (item.HomeCinemaID == theatr.HomeCinemaID)
                                {

                                    <tr>
                                        <td>
                                            @Html.DisplayName(theatr.TheatersName)
                                        </td>
                                        <td>
                                            <span>&nbsp;</span>
                                        </td>
                                        <td>
                                            @Html.ActionLink("Details", "Details", "Theatres", new { id = theatr.MovieTheatersID }, null)
                                        </td>
                                    </tr>

                                }
                            }

                        </table>
                    }
                </td>
                <td>
                    @Html.DisplayFor(model=>item.Showing)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.HomeCinemaID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.HomeCinemaID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.HomeCinemaID })
                </td>
            </tr>
        }

    </table>
</div>

CimenaCityProject/Views/HomeCinema/IndexSorted.cshtml
@using CimenaCityProject.Models
@model IEnumerable<CimenaCityProject.Models.HomeCinema>

    <table class="table">
        @{  HomeCinemaContext db = new HomeCinemaContext();}
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CinemaName)
                </td>
                <td>
                    @db.CityList.Where(x => x.CityID == item.CityID).SingleOrDefault().EnglishName
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                </td>
                <td>
                    @{
                        <table class="table">
                            @foreach (var theatr in db.Theaters)
                            {
                                if (item.HomeCinemaID == theatr.HomeCinemaID)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayName(theatr.TheatersName)
                                        </td>
                                        <td>
                                            <span>&nbsp;</span>
                                        </td>
                                        <td>
                                            @Html.ActionLink("Details", "Details", "Theatres", new { id = theatr.MovieTheatersID }, null)
                                        </td>
                                    </tr>

                                }
                            }

                        </table>
}
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.HomeCinemaID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.HomeCinemaID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.HomeCinemaID })
                </td>
            </tr>
        }

    </table>