CimenaCityProject/Models/MovieShowTime.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;


using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CimenaCityProject.Models
{
    /// <summary>
    /// Describing the Time each Movie will show up
    /// </summary>
    public class MovieShowTime
    {
        public MovieShowTime()
        {
            this.Events = new HashSet<Event>();
            this.TimeScreening = new HashSet<TimeScreening>();
        }

        public int MovieShowTimeID { get; set; }
        public int MovieID { get; set; }
        public System.DateTime ShowTime { get; set; }
        public bool IsDisplay { get; set; }

        public virtual ICollection<Event> Events { get; set; }
        public virtual Movie Movie { get; set; }
        public virtual ICollection<TimeScreening> TimeScreening { get; set; }
    }
}

CimenaCityProject/Controllers/MovieShowTimeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CimenaCityProject.Models;
using CimenaCityProject.ViewModels;

namespace CimenaCityProject.Controllers
{
    public class MovieShowTimeController : Controller
    {
        private HomeCinemaContext db = new HomeCinemaContext();

        // GET: /MovieShowTime/
        public ActionResult Index(int? id, int? MovieShowTimeID)
        {
            var viewMovieQry = new MovieData();

            viewMovieQry.Movie = (from me in db.Movies
                                  orderby me.MovieID 
                                  select me).ToArray();

            viewMovieQry.MovieShowTime = (from mst in db.MovieShowTimes
                                          orderby mst.ShowTime.Hour
                                          select mst).ToArray();

            //select * movieShowTime only movie by the ID 
            if (id != null)
            {
                ViewBag.MovieDataID = id.Value;
                viewMovieQry.Movie = (from me in db.Movies
                                      where me.MovieID == id.Value
                                      select me);

                viewMovieQry.MovieShowTime = (from mst in db.MovieShowTimes
                                              where mst.MovieID == id.Value
                                              orderby mst.ShowTime
                                              select mst).ToArray();
            }

            // get spesific movieShowTime by his ID 
            if (MovieShowTimeID != null)
            {
                ViewBag.movieShowTimeID = MovieShowTimeID.Value;
                viewMovieQry.MovieShowTime = (from me in db.MovieShowTimes
                                      where me.MovieShowTimeID == id.Value
                                      select me);
            }

            return View(viewMovieQry);
        }

        // GET: /MovieShowTime/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }


            var viewMovieQry = new MovieData();

            viewMovieQry.Movie = (from me in db.Movies
                                  where me.MovieID == id
                                  select me).ToArray();
            viewMovieQry.MovieShowTime = (from mst in db.MovieShowTimes
                                          where mst.MovieID == id
                                          select mst).ToArray();


            ViewBag.MovieName = viewMovieQry.Movie.Where(mov => mov.MovieID == id).Single().MovieName;
            // MovieShowTime movieshowtime = db.MovieShowTimes.Find(id);

            if (viewMovieQry.MovieShowTime == null)
            {
                return HttpNotFound();
            }
            return View(viewMovieQry);
        }

        // GET: /MovieShowTime/Create
        public ActionResult Create(int? id)
        {

            //declare the SelectListItem for the dropdown 
            List<SelectListItem> movieListItems = new List<SelectListItem>();

            if (id == null)
            {
                var movieList = (from movie
                            in db.Movies
                                 select movie);

                foreach (var movieListTemp in movieList)
                {
                    //add value'a for the SelectListItem
                    movieListItems.Add(new SelectListItem
                    {
                        Text = movieListTemp.MovieName,
                        Value = movieListTemp.MovieID.ToString()
                    });
                }
            }
            else
            {
                // get all the Movie via ID
                var movieList = (from movie
                           in db.Movies
                                 where movie.MovieID == id
                                 select movie);

                foreach (var movieListTemp in movieList)
                {
                    //add value'a for the SelectListItem
                    movieListItems.Add(new SelectListItem
                    {
                        Text = movieListTemp.MovieName,
                        Value = movieListTemp.MovieID.ToString()
                    });
                }
            }

            //send the data via ViewData key: movieList 
            ViewData.Add("movieList", movieListItems);


            return View();
        }

        // POST: /MovieShowTime/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(string movieList, List<DateTime> ShowTime, [Bind(Include = "MovieShowTimeID,MovieID,ShowTime")] MovieShowTime movieshowtime)
        {

            if (ShowTime.Count != 0)
            {
                // create list of Movie Show Time     
                List<MovieShowTime> MovieShowTimeList = new List<MovieShowTime>();

                foreach (var item in ShowTime)
                {
                    if (item.Date != Convert.ToDateTime("01/01/0001 00:00:00"))
                    {

                        MovieShowTime ShowTimeItem = new MovieShowTime();
                        // add Detials 
                        ShowTimeItem.MovieID = Convert.ToInt32(movieList);
                        ShowTimeItem.ShowTime = item;

                        // add Show Time Item's for the List 
                        MovieShowTimeList.Add(ShowTimeItem);
                    }
                }

                //Add all the Item's to DB . 
                if (ModelState.IsValid)
                {
                    foreach (var item in MovieShowTimeList)
                    {
                        db.MovieShowTimes.Add(item);
                        db.SaveChanges();
                    }
                    return RedirectToAction("Index", "Movie");
                }
                else
                {
                    ViewBag.ErrorMessage = "Unable to add all the Time's";
                    return RedirectToAction("Create", "Movie");
                }
            }
            else
            {
                ViewBag.ErrorMessage = "Unable to add Movie Show Time";
            }

            return View(movieshowtime);
        }


        // GET: /MovieShowTime/Edit/5
        public ActionResult Edit(int? id)
        {
            int? movieID;
            string movieName;

            if (TempData.ContainsKey("MovieID"))
            {
                 movieID = (int)TempData["MovieID"];
                 movieName = (from me in db.Movies
                              where me.MovieID == movieID
                              orderby me.MovieID
                              select me.MovieName).SingleOrDefault().ToString();
            }
            else
            {

                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                movieName = (from me in db.Movies
                             where me.MovieID == (from mst in db.MovieShowTimes
                                                  where mst.MovieShowTimeID == id.Value 
                                                  select mst.MovieID).FirstOrDefault()
                             orderby me.MovieID
                             select me.MovieName).SingleOrDefault().ToString();
            }

           
           
            ViewBag.MovieName = movieName;

            MovieShowTime movieshowtime = db.MovieShowTimes.Find(id);

            if (movieshowtime == null)
            {
                return HttpNotFound();
            }
            return View(movieshowtime);

        }

        // POST: /MovieShowTime/Edit/5
        [HttpPost]
        // [ValidateAntiForgeryToken]
        public ActionResult Edit(string newShowTimme, [Bind(Include = "MovieShowTimeID,MovieID,ShowTime")] MovieShowTime movieshowtime)
        {

            if (newShowTimme != null || newShowTimme != string.Empty)
            {
                 try
                {
                    movieshowtime.ShowTime = Convert.ToDateTime(newShowTimme);
                }
                catch (Exception)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.NoContent);
              
                } 
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.ExpectationFailed);
            }

            if (ModelState.IsValid)
            {
                db.Entry(movieshowtime).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(movieshowtime);
        }

        // GET: /MovieShowTime/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MovieShowTime movieshowtime = db.MovieShowTimes.Find(id);
            if (movieshowtime == null)
            {
                return HttpNotFound();
            }
            return View(movieshowtime);
        }

        // POST: /MovieShowTime/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MovieShowTime movieshowtime = db.MovieShowTimes.Find(id);
            db.MovieShowTimes.Remove(movieshowtime);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        protected override void Dispose(bool disposing)
        {

CimenaCityProject/Views/MovieShowTime/Create.cshtml
@using CimenaCityProject.ViewModels;
@model CimenaCityProject.Models.MovieShowTime

@{
    ViewBag.Title = "Movie Show Time";
}

<link rel="stylesheet" type="text/css" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>


<h2>Enter the New next</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Movie Name
            <div class="col-md-10" style="color:black" id="SelectedValue">
               @Html.DropDownList("movieList" )
            </div>
        </div>

        <div class="form-group">
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Add The Show Time for the Movie
            <div class="col-md-10" id="ShowTime">
                @Html.TextBoxFor(model => model.ShowTime, new { @id = "ShowTime" })
                @Html.ValidationMessageFor(model => model.ShowTime)              
            </div>
            <br />
            <div class="col-md-10" id="ShowTime">
                @Html.TextBoxFor(model => model.ShowTime, new { @id = "ShowTime" })
                @Html.ValidationMessageFor(model => model.ShowTime)            
            </div>
            <br />
            <div class="col-md-10" id="ShowTime">
                @Html.TextBoxFor(model => model.ShowTime, new { @id = "ShowTime" })
                @Html.ValidationMessageFor(model => model.ShowTime)
            </div>
            <br />
            <div class="col-md-10" id="ShowTime">
                @Html.TextBoxFor(model => model.ShowTime, new { @id = "ShowTime" })
                @Html.ValidationMessageFor(model => model.ShowTime)
            </div>
            <br />
        </div>
       
   
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" id="addShowTime" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script>
    $(function () {
        $('#timepicker').timepicker();
    });


    $('addShowTime').click(function () {
        var list = [];
        $('div.ShowTime').find("input:text").each(function () {
            list.push($(this).val())
        })
        var key = { listkey: list }
        $.ajax({
            url: '@Url.Action("Index","Movie")',
            traditional: true,
            data: list,
            datatype: "html",
            success: function (data) {
                alert('success')
            },
            error: function (data) {
                alert('fail')
            }
        })
    });
    
</script>

CimenaCityProject/Views/MovieShowTime/Delete.cshtml
@model CimenaCityProject.Models.MovieShowTime

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MovieShowTime</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MovieID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MovieID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShowTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShowTime)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CimenaCityProject/Views/MovieShowTime/Details.cshtml
@model CimenaCityProject.ViewModels.MovieData

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>MovieShowTime</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Movie &nbsp; - @ViewBag.MovieName
        </dt>

        <dd>
          
            <br />
            @{
                if (Model.Movie.Where(me => me.PictureLarge == me.PictureLarge).SingleOrDefault().PictureLarge != null)
                {
                    var base64 = Convert.ToBase64String(Model.Movie.Where(me => me.PictureLarge == me.PictureLarge).SingleOrDefault().PictureLarge);
                    var imgSrc = String.Format("data:image/gif;base64,{0}", base64);

                    <img src="@imgSrc" alt="Unable to display" />
                    <br />
                }
            }
            <br />
            <br />
        </dd>

        <dt>
            Show Time
        </dt>

        <dd>


            <table class=" table-striped" style="font-size:larger">
                @foreach (var item in Model.MovieShowTime)
                {

                    <tr>
                        <td>@item.ShowTime.TimeOfDay</td><td>&nbsp;&nbsp;&nbsp;</td>
                        <td>@Html.ActionLink("Edit", "Edit", "MovieShowTime", new { id = item.MovieShowTimeID }, null)
                            <br /></td>

                    </tr>
                   
                }
            </table>

        </dd>

    </dl>
</div>
<p>


    |  @Html.ActionLink("Back to List", "Index")
</p>

CimenaCityProject/Views/MovieShowTime/Edit.cshtml
@model CimenaCityProject.Models.MovieShowTime

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MovieShowTime</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.MovieShowTimeID)
        @Html.HiddenFor(model => model.MovieID)
        <div class="form-group">
           
            <div class="col-md-10">
                @ViewBag.MovieName
                @Html.ValidationMessageFor(model => model.MovieID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShowTime, new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                Old time @Html.Label(Model.ShowTime.TimeOfDay.ToString())
                <br /><br />               
                <input type="time" id="newShowTimme"
                       name="newShowTimme"
                       onkeypress="CheckEntry(event,/[a-zA-z]/,'only this time format HH:mm:ssss')" />

            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default"  />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CimenaCityProject/Views/MovieShowTime/Index.cshtml
@using CimenaCityProject.Models
@model CimenaCityProject.ViewModels.MovieData

@{
    ViewBag.Title = "Show Time";
}

<h2>Movie Show Time</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
          Movie Name
        </th>
        <th>
          Realse Date 
        </th>
        <th>
            Show Time
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.Movie) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MovieName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReleaseDate)
        </td>
        <td>
            @{
             foreach (var showTime in Model.MovieShowTime)
             {
                 if (showTime.MovieID == item.MovieID)
                    {
                        @showTime.ShowTime.TimeOfDay  @Html.ActionLink("|  Edit", "Edit", new { id = showTime.MovieShowTimeID }, TempData["MovieID"]=showTime.MovieID ) 
                <br />
                    }
               }
            }
        </td>
        <td>
            @*@Html.ActionLink("Edit", "Edit", new { id=item.MovieID }) |*@
            @Html.ActionLink("Details", "Details", new { id = item.MovieID }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.MovieID })
        </td>
    </tr>
}

</table>