CimenaCityProject/Models/TimeScreening.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace CimenaCityProject.Models
{
    public class TimeScreening
    {

        public TimeScreening()
        {
        }

        public int TimeScreeningID { get; set; }
        public int MovieShowTimeID { get; set; }
        public int MovieTheatersID { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Price { get; set; }
        public bool IsDisplayed { get; set; }

        public virtual MovieShowTime MovieShowTime { get; set; }
        public virtual MovieTheaters MovieTheaters { get; set; }
        public virtual Order Order { get; set; }

    }
}

CimenaCityProject/Controllers/TimeScreeningController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

using CimenaCityProject.Models;
using CimenaCityProject.ViewModels;
using CimenaCityProject.Logic;

namespace CimenaCityProject.Controllers
{
    public class TimeScreeningController : Controller
    {
        private HomeCinemaContext db = new HomeCinemaContext();

        // GET: /TimeScreening/
        public ActionResult Index(string Error)
        {
            TempData.Clear();
            bool flag = false;
            TempData.Add("flagDisplay", flag);
            TempData.Add("flagMovieName", flag);
            TempData.Add("flagTime", flag);
            TempData.Add("flagHomeCinema", flag);
            TempData.Add("flagTheaters", flag);
            TempData.Add("flagDate", flag);
            TempData.Add("flagPrice", flag);

            TimeScreeningData timeScreening = new TimeScreeningData();

            if (!string.IsNullOrEmpty(Error))
            {
                TempData["msg"] = "<script>alert('" + Error + "');</script>";
            }

            return View(timeScreening);
        }

        // POST: /TimeScreening/
        [HttpPost]
        public ActionResult Index(string searchByMovie, string searchByHomeCinema,string sortingOrder)
        {
            TimeScreeningData timeScreening;

            //search by movie or homeCinema
            if (!string.IsNullOrEmpty(searchByMovie) && !string.IsNullOrEmpty(searchByHomeCinema))
            {
                timeScreening = new TimeScreeningData(null, searchByMovie, searchByHomeCinema);
            }
            else if (!string.IsNullOrEmpty(searchByMovie))
            {
                timeScreening = new TimeScreeningData(null, searchByMovie, null);
            }
            else if (!string.IsNullOrEmpty(searchByHomeCinema))
            {
                timeScreening = new TimeScreeningData(null, null, searchByHomeCinema);
            }
            else
            {
                timeScreening = new TimeScreeningData(null, null, null);
            }

          
            return View(timeScreening);
        }
        
        // GET: /TimeScreening/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TimeScreening timescreening = db.TimeScreening.Find(id);
            if (timescreening == null)
            {
                return HttpNotFound();
            }
            return View(timescreening);
        }

        // GET: /TimeScreening/Create
        public ActionResult Create(int? number)
        {
            // i need to edit the create for i can add a multiplay timeScteening 
            ViewBag.number = number;
            ViewBag.HomeCinemaID = new SelectList(db.HomeCinemas, "HomeCinemaID", "CinemaName");
            ViewBag.MovieID = new SelectList(db.Movies, "MovieID", "MovieName");
            return View();
        }

        // GET: /TimeScreening/Create

        public PartialViewResult CreateOneTimeScreen(string Error)
        {
            if (!string.IsNullOrEmpty(Error))
            {
                ViewBag.Error = Error;
            }
            ViewBag.HomeCinemaID = new SelectList(db.HomeCinemas, "HomeCinemaID", "CinemaName");
            ViewBag.MovieID = new SelectList(db.Movies, "MovieID", "MovieName");
            return PartialView("CreateOneTimeScreen");
        }

        // POST: /TimeScreening/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TimeScreeningID,MovieShowTimeID,TheatresID,Date,Price,IsDisplayed")] TimeScreening Timescreening, int MovieTheatersID)
        {
            if ( Timescreening.MovieTheatersID == 0)
            {
                Timescreening.MovieTheatersID = MovieTheatersID;
            }
            MovieShowTime movieshowtime = db.MovieShowTimes.Find(Timescreening.MovieShowTimeID);
            HomeCinema homecinema = db.HomeCinemas.Where(x => x.HomeCinemaID == db.Theaters.Where(y => y.MovieTheatersID == Timescreening.MovieTheatersID).FirstOrDefault().HomeCinemaID).FirstOrDefault();
            MovieTheaters theatres = db.Theaters.Find(MovieTheatersID);
            if (Timescreening.IsDisplayed == true)
            {
                theatres.IsActive = true;
                movieshowtime.IsDisplay = true;
                homecinema.Showing = true;
            }
            
                if (ModelState.IsValid)
                {
                    db.TimeScreening.Add(Timescreening);
                    db.Entry(movieshowtime).State = EntityState.Modified;
                    db.Entry(theatres).State = EntityState.Modified;
                    db.Entry(homecinema).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return RedirectToAction("Index", new { Error = "You Cant add a Contract now. try again later. " });
        }

        // GET: /TimeScreening/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            TimeScreening timescreening = db.TimeScreening.Find(id); 
            
            if (timescreening == null)
            {
                return HttpNotFound();
            }
            ViewBag.HomeCinemaID = new SelectList(db.HomeCinemas, "HomeCinemaID", "CinemaName",timescreening.MovieTheaters.HomeCinema.CinemaName);
            ViewBag.MovieID = new SelectList(db.Movies, "MovieID", "MovieName",timescreening.MovieShowTime.Movie.MovieName);
            return View(timescreening);
        }

        // POST: /TimeScreening/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TimeScreeningID,MovieShowTimeID,TheatresID,Date,Price,IsDisplayed")] TimeScreening timescreening, int? MovieTheatersID)
        {
            timescreening.MovieTheatersID = MovieTheatersID.Value;


            if (ModelState.IsValid)
            {
                db.Entry(timescreening).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(timescreening);
        }

        // GET: /TimeScreening/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TimeScreening timescreening = db.TimeScreening.Find(id);
            if (timescreening == null)
            {
                return HttpNotFound();
            }
            return View(timescreening);
        }

        // POST: /TimeScreening/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TimeScreening timescreening = db.TimeScreening.Find(id);
            db.TimeScreening.Remove(timescreening);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //auto complete for movie name 
        public JsonResult GetMovieName(string term)
        {
            List<string> movieName;
            movieName = db.Movies.Where(x => x.MovieName.Contains(term))
                .Select(y => y.MovieName).ToList();

            return Json(movieName, JsonRequestBehavior.AllowGet);
        }
        //auto complete for Cinema
        public JsonResult GetHomeCinemaName(string term)
        {

            List<string> HomeCinemaName;
            HomeCinemaName = db.HomeCinemas.Where(x => x.CinemaName.Contains(term))
                .Select(y => y.CinemaName).ToList();

            return Json(HomeCinemaName, JsonRequestBehavior.AllowGet);
        }

       // get the theatres for CreatePage via cinema id 
        public ActionResult GetTheatres(int? CinemaID)
        {
            var data = (from d in db.Theaters
                        where d.HomeCinemaID == CinemaID
                        select new
                        {
                            id = d.MovieTheatersID,
                            name = d.TheatersName 
                        }).ToList();

            return Json(data,JsonRequestBehavior.AllowGet);
        }

        // get the showtime for CreatePage via movie id
        public JsonResult GetShowTime(int? MovieID)
        {

            var data = (from m in db.MovieShowTimes
                        where m.MovieID == MovieID
                        select new
                        {
                            id = m.MovieShowTimeID,
                            name = m.ShowTime
                        }).ToList();
                
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        // get the showtime for CreatePage via movie id
        public JsonResult CheckIfContractExist(int TheatresID , int ShowTimeID)
        {
            var data = EcomLogic.CheckIfTheContractExist(TheatresID, ShowTimeID);

            return Json(data, JsonRequestBehavior.AllowGet);
        }


        // getting the table view after sorting
        public PartialViewResult SortingIndexResult(TimeScreeningData timeScreening, string sortingOrder)
        {
            bool flagDisplay = false, flagMovieName = false, flagTime = false, flagHomeCinema = false, flagTheaters = false, flagDate = false, flagPrice = false;

            if (TempData["flagDisplay"] != null ||TempData["flagMovieName"] != null ||TempData["flagTime"] != null ||TempData["flagHomeCinema"] != null ||
                TempData["flagTheaters"] != null ||TempData["flagDate"] != null ||TempData["flagPrice"] != null  )
            {

CimenaCityProject/Views/TimeScreening/AskQuestion.cshtml
@using(Html.BeginForm("Create","TimeScreening", FormMethod.Get,new{id="Question",name="Question"}))
{
    <span>how many Time screening you need to enter?</span>
    <input type="number" id="number" name="number" value=" " />
    <input type="submit" id="Question" name="Question" value="ok"/>
}

CimenaCityProject/Views/TimeScreening/Create.cshtml
@model List<CimenaCityProject.Models.TimeScreening>

@{
    ViewBag.Title = "Create";
    int? numberOfNewTimeScreening = ViewBag.number;
    if (!numberOfNewTimeScreening.HasValue)
    {
        numberOfNewTimeScreening = 1;
    }

    for (int i = 0; i < numberOfNewTimeScreening; i++)
    {
        
    }
    
    var SelectMovieID = (SelectList)ViewBag.MovieID;
    var SelectHomeCinemaID = (SelectList)ViewBag.HomeCinemaID;
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "TimeScreening", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>TimeScreening</h4>
        <hr />
        @Html.ValidationSummary(true)
        <table>
            <tr>
                <th>
                    @Html.Label("ShowTime", new { @class = "control-label col-md-2" })
                </th>
                <th>
                    @Html.Label("Theatres", new { @class = "control-label col-md-2" })
                </th>
                <th>
                    @Html.Label("Date", new { @class = "control-label col-md-2" })
                </th>
                <th>
                    @Html.Label("Price", new { @class = "control-label col-md-2" })
                </th>
                <th>
                    @Html.Label("Is Displayed", new { @class = "control-label col-md-2" })
                </th>
                <th>
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </th>
            </tr>

            @for (int i = 0; i < numberOfNewTimeScreening.Value; i++)
            {
                string HomeCinemaID = "["+i + "].HomeCinemaID".ToString();
                string TheatresID = "[" + i + "].MovieTheatersID".ToString();   
                 
                <tr>
                    <td>
                        <div class="col-sm-8">
                            <br />
                            @Html.DropDownListFor(model => model[i].MovieShowTime.MovieID, SelectMovieID, "Select Movie")
                            <br /><br />
                            @Html.DropDownListFor(model => model[i].MovieShowTimeID, Enumerable.Empty<SelectListItem>(), "--Loading Value--")
                            @Html.ValidationMessageFor(model => model[i].MovieShowTimeID)
                        </div>
                    </td>
                    <td>
                        <div class="col-sm-8">
                            <br />
                            @Html.DropDownListFor(model => int.Parse(model[i].MovieTheaters.HomeCinemaID.ToString()), SelectHomeCinemaID, "Select Home Cinema", new { @class = HomeCinemaID })
                            <br /><br />
                            @Html.DropDownListFor(model => int.Parse(model[i].MovieTheatersID.ToString()), Enumerable.Empty<SelectListItem>(), "--Loading Value--", new { @class = TheatresID })
                            @Html.ValidationMessageFor(model => model[i].MovieTheatersID)
                        </div>
                    </td>
                    <td>
                        <div class="col-sm-8">
                            <br />
                            @Html.EditorFor(model => model[i].Date)
                            @Html.ValidationMessageFor(model => model[i].Date)
                        </div>
                    </td>
                    <td>
                        <div class="col-sm-8">
                            <br />
                            @Html.EditorFor(model => model[i].Price)
                            @Html.ValidationMessageFor(model => model[i].Price)
                        </div>
                    </td>
                    <td>
                        <div class="col-sm-8">
                            <br />
                            @Html.EditorFor(model => model[i].IsDisplayed)
                            @Html.ValidationMessageFor(model => model[i].IsDisplayed)
                        </div>
                    </td>
                    <td></td>
                </tr>
            }
        </table>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.min.js"></script>
@{
    for (var j = 0; j < numberOfNewTimeScreening; j++)
    {
        string HomeCinemaID = "#[" + j + "].HomeCinemaID";
        string TheatresID = "[" + j + "].MovieTheatersID";  
           
<script type="text/javascript">
    $(function () {
        $('@HomeCinemaID').change(function () {
            alert("ok")
        });
       });



        $(function () {
            $('@HomeCinemaID').change(function () {
                alert("ok1")
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetTheatres","TimeScreening")',
                    data: { CinemaID: $('@HomeCinemaID').val() },
                    success: function (data) {
                        $(@TheatresID).html('');
                        $.each(data, function (id, option) {
                            $(@TheatresID).append($('<option></option>').val(option.id).html(option.name));
                        });
                    },
                    error: function (xhr, ajaxOptions, thrownEror) {
                        alert("Error by loading the Theatres");
                    }
                });
            });
       });


        $(function () {
            $('#'+j + '.MovieID').change(function () {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetShowTime", "TimeScreening")',
                    data: { MovieID: $('#' + j + '.MovieID').val() },
                    dataType: 'json',
                    success: function (data) {
                        $('#' + j + '.MovieShowTimeID').html('');
                        $.each(data, function (id, option) {
                            var name = DatetimeConverter(option.name)
                            $('#' + j + '.MovieShowTimeID').append($('<option></option>').val(option.id).html(name));
                        });

                    },
                    error: function (xhr, ajaxOptions, thrownEror) {
                        alert("False" + xhr + "..." + ajaxOptions + "... " + thrownEror);
                    }
                });
            });
        });

    
    // START Datetime Converters
    function DateConverter(date) {
        var aux = null;
        if (date != null) {
            aux = date.substring(6);
            aux = aux.substring(0, aux.indexOf(')'));
        }

        return aux != null ? getISODate(new Date(parseInt(aux))) : "";
    }

    function DatetimeConverter(date) {
        var aux = null;
        if (date != null) {
            aux = date.substring(6);
            aux = aux.substring(0, aux.indexOf(')'));
        }
        return aux != null ? getISODateTime(new Date(parseInt(aux))) : "";
    }

    function getISODate(d) {
        // padding function
        var s = function (a, b) { return (1e15 + a + "").slice(-b) };

        // default date parameter
        if (typeof d === 'undefined') {
            d = new Date();
        };

        // return ISO datetime
        return zeroPad(d.getDate(), 2) + '/' +
        zeroPad(s(d.getMonth() + 1, 2), 2) + '/' +
        zeroPad(d.getFullYear(), 4);
    }

    function getISODateTime(d) {
        // padding function
        var s = function (a, b) { return (1e15 + a + "").slice(-b) };

        // default date parameter
        if (typeof d === 'undefined') {
            d = new Date();
        };

        // return ISO datetime
        return zeroPad(d.getHours(), 2) + ":" +
        zeroPad(d.getMinutes(), 2) + ":" +
        zeroPad(d.getSeconds(), 2);
    }

    function zeroPad(num, places) {
        var zero = places - num.toString().length + 1;
        return Array(+(zero > 0 && zero)).join("0") + num;
    }
    // END Datetime Converters


</script>
    }
    }

CimenaCityProject/Views/TimeScreening/CreateOneTimeScreen.cshtml
@model CimenaCityProject.Models.TimeScreening

@{
    var SelectMovieID = (SelectList)ViewBag.MovieID;
    var SelectHomeCinemaID = (SelectList)ViewBag.HomeCinemaID;
}

@using (Html.BeginForm("Create", "TimeScreening", FormMethod.Post, new { id = "CreateOne", name = "CreateOne" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true)
        <table>
            <tr>
                <th>
                    @Html.Label("Theatres", new { @class = "control-label col-md-2" })
                </th>
                <th>
                    @Html.Label("ShowTime", new { @class = "control-label col-md-2" })
                </th>

                <th>
                    @Html.Label("Date", new { @class = "control-label col-md-2" })
                </th>
                <th>
                    @Html.Label("Price", new { @class = "control-label col-md-2" })
                </th>
                <th>
                    @Html.Label("Is Displayed", new { @class = "control-label col-md-2" })
                </th>
                <th>
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" id="NewTimeScreen" />
                    </div>
                </th>
            </tr>

            <tr>
                <td>
                    <div class="col-sm-8">
                        <br />
                        @Html.DropDownList("HomeCinemaID", SelectHomeCinemaID, "Select Home Cinema", new { id = "HomeCinemaID", name = "HomeCinemaID" })
                        <br /><br />
                        @Html.DropDownListFor(model => model.MovieTheatersID, Enumerable.Empty<SelectListItem>()
                                                   , "--Loading Value--", new { id = "TheatresName", name = "TheatresName" })
                        @Html.ValidationMessageFor(model => model.MovieTheatersID)
                    </div>
                </td>
                <td>
                    <div class="col-sm-8">
                        <br />
                        @Html.DropDownList("MovieID", SelectMovieID, "Select Movie", new { id = "MovieID", name = "MovieID" })
                        <br /><br />
                        @Html.DropDownListFor(model => model.MovieShowTimeID, Enumerable.Empty<SelectListItem>()
                                                  , "--Loading Value--", new { id = "ShowTime", name = "ShowTime" })
                        @Html.ValidationMessageFor(model => model.MovieShowTimeID)
                    </div>
                </td>

                <td>
                    <div class="col-sm-8">
                        <br />
                        @Html.TextBoxFor(model => model.Date, new { @class = "datepicker" })
                        @Html.ValidationMessageFor(model => model.Date)
                    </div>
                </td>
                <td>
                    <div class="col-sm-8">
                        <br />
                        @Html.EditorFor(model => model.Price)
                        @Html.ValidationMessageFor(model => model.Price)
                    </div>
                </td>
                <td>
                    <div class="col-sm-8">
                        <br />
                        @Html.EditorFor(model => model.IsDisplayed)
                        @Html.ValidationMessageFor(model => model.IsDisplayed)
                    </div>
                </td>
                <td></td>
            </tr>

        </table>
    </div>
}


<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.min.js"></script>

<link rel="stylesheet" type="text/css" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<script type="text/javascript">
    $(function () {
        $('#Date').datepicker({
            dateFormat: 'dd/MM/yy',
            showOtherMonths: true,
            selectOtherMonths: true
        });
    });
</script>


<script type="text/javascript">

    $(function () {
        $('#HomeCinemaID').change(function () {
            $.ajax({
                type: "POST",
                url: '@Url.Action("GetTheatres","TimeScreening")',
                data: { CinemaID: $('#HomeCinemaID').val() },
                success: function (data) {
                    $('#TheatresName').html('');
                    $('#TheatresName').append($('<option></option>').val(0).html("Pick a Theatr"));
                    $.each(data, function (id, option) {
                        $('#TheatresName').append($('<option></option>').val(option.id).html(option.name));
                    });
                },
                error: function (xhr, ajaxOptions, thrownEror) {
                    alert("Error by loading the Theatres");
                }
            });
        });
    });



    $(function () {
        $('#MovieID').change(function () {
            $.ajax({
                type: "POST",
                url: '@Url.Action("GetShowTime", "TimeScreening")',
                data: { MovieID: $('#MovieID').val() },
                dataType: 'json',
                success: function (data) {
                    $('#ShowTime').html('');
                    $('#ShowTime').append($('<option></option>').val(0).html("Pick a time"));
                    $.each(data, function (id, option) {
                        var name = DatetimeConverter(option.name)
                        $('#ShowTime').append($('<option></option>').val(option.id).html(name));
                    });

                },
                error: function (xhr, ajaxOptions, thrownEror) {
                    alert("False" + xhr + "..." + ajaxOptions + "... " + thrownEror);
                }
            });
        });
    });


    $(function () {
        $('#ShowTime').change(function () {
            $.ajax({
                type: "POST",
                url: '@Url.Action("CheckIfContractExist", "TimeScreening")',
                data: {
                    TheatresID: $('#TheatresName').val(),
                    ShowTimeID: $('#ShowTime').val()
                },
                dataType: 'json',
                success: function (data) {
                    if (data == true) {
                        alert("This Theatr Alredy exist in another contact /n Please Chosee another Theatre or another time.")
                        $('#ShowTime').html('')
                        $('#TheatresName').html('')
                        $('#ShowTime').append($('<option></option>').val(0).html("Pick a Movie"));
                        $('#TheatresName').append($('<option></option>').val(0).html("Pick a HomeCinema"));
                    }
                },
                error: function (xhr, ajaxOptions, thrownEror) {
                    alert("False" + xhr + "..." + ajaxOptions + "... " + thrownEror);
                }
            });
        });
    });


    // Get the Price For each type of movie
    $(function () {
        $('#TheatresName').change(function () {
            var ParamName = $('#TheatresName').text();
            if (/MAX/.test(ParamName) || /Max/.test(ParamName) || /MAx/.test(ParamName) || /max/.test(ParamName)
                || /mAx/.test(ParamName) || /maX/.test(ParamName) || /mAX/.test(ParamName))
            {
                document.getElementById('Price').value = 43
            }
            else if (/VIP/.test(ParamName) || /VIp/.test(ParamName)
            || /vIP/.test(ParamName) )
            {
               document.getElementById('Price').value = 38
            }
            else
            {
                document.getElementById('Price').value = 35
            }
        });
    });


    // START Datetime Converters
    function DateConverter(date) {
        var aux = null;
        if (date != null) {
            aux = date.substring(6);
            aux = aux.substring(0, aux.indexOf(')'));
        }

        return aux != null ? getISODate(new Date(parseInt(aux))) : "";
    }

    function DatetimeConverter(date) {
        var aux = null;
        if (date != null) {
            aux = date.substring(6);
            aux = aux.substring(0, aux.indexOf(')'));
        }
        return aux != null ? getISODateTime(new Date(parseInt(aux))) : "";
    }

    function getISODate(d) {
        // padding function
        var s = function (a, b) { return (1e15 + a + "").slice(-b) };

        // default date parameter
        if (typeof d === 'undefined') {
            d = new Date();
        };

        // return ISO datetime
        return zeroPad(d.getDate(), 2) + '/' +
        zeroPad(s(d.getMonth() + 1, 2), 2) + '/' +
        zeroPad(d.getFullYear(), 4);
    }

    function getISODateTime(d) {
        // padding function
        var s = function (a, b) { return (1e15 + a + "").slice(-b) };

        // default date parameter
        if (typeof d === 'undefined') {
            d = new Date();
        };

        // return ISO datetime
        return zeroPad(d.getHours(), 2) + ":" +
        zeroPad(d.getMinutes(), 2) + ":" +
        zeroPad(d.getSeconds(), 2);
    }

    function zeroPad(num, places) {
        var zero = places - num.toString().length + 1;
        return Array(+(zero > 0 && zero)).join("0") + num;
    }
    // END Datetime Converters


</script>

CimenaCityProject/Views/TimeScreening/Delete.cshtml
@model CimenaCityProject.Models.TimeScreening

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TimeScreening</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MovieShowTimeID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MovieShowTimeID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MovieTheatersID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MovieTheatersID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDisplayed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDisplayed)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CimenaCityProject/Views/TimeScreening/Details.cshtml
@model CimenaCityProject.Models.TimeScreening

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>TimeScreening</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MovieShowTimeID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MovieShowTimeID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MovieTheatersID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MovieTheatersID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDisplayed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDisplayed)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.TimeScreeningID }) |
    @Html.ActionLink("Back to List", "Index")
</p>